# Generated by Django 5.2.11 on 2026-02-28 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlightPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Active Mission', max_length=100)),
                ('altitude', models.IntegerField(default=2)),
                ('speed', models.IntegerField(default=30)),
                ('mode', models.CharField(default='Stabilize', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FlightStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('step_type', models.CharField(max_length=50)),
                ('step_val', models.CharField(default='0', max_length=255)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='missions.flightplan')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
