# Generated by Django 5.2.11 on 2026-02-28 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelemetrySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('connected', models.BooleanField(default=False)),
                ('battery', models.IntegerField(blank=True, null=True)),
                ('altitude_m', models.FloatField(blank=True, null=True)),
                ('raw', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['-recorded_at'], name='telemetry_t_recorde_9974d1_idx'), models.Index(fields=['connected', '-recorded_at'], name='telemetry_t_connect_a3f8bd_idx')],
            },
        ),
    ]
