# Generated by Django 5.2.11 on 2026-02-28 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0002_telemetrysnapshot_gps_lat_telemetrysnapshot_gps_lon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telemetrysnapshot',
            name='agx',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='telemetrysnapshot',
            name='agy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='telemetrysnapshot',
            name='agz',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='telemetrysnapshot',
            name='baro',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='telemetrysnapshot',
            name='flight_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='telemetrysnapshot',
            name='templ_c',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='telemetrysnapshot',
            name='vgx',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='telemetrysnapshot',
            name='vgy',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='telemetrysnapshot',
            name='vgz',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
