# Generated by Django 5.2.11 on 2026-04-09 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0003_telemetrysnapshot_agx_telemetrysnapshot_agy_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveSystemState',
            fields=[
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('gps_lat', models.FloatField(blank=True, null=True)),
                ('gps_lon', models.FloatField(blank=True, null=True)),
                ('ble_active', models.BooleanField(default=False)),
            ],
        ),
    ]
