# Generated by Django 5.2.11 on 2026-04-09 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0004_livesystemstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='livesystemstate',
            name='last_error',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
