# Generated by Django 5.2.11 on 2026-04-10 06:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0005_livesystemstate_last_error'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telemetrysnapshot',
            options={'ordering': ['-recorded_date', '-recorded_time']},
        ),
        migrations.RemoveIndex(
            model_name='telemetrysnapshot',
            name='telemetry_t_recorde_9974d1_idx',
        ),
        migrations.RemoveIndex(
            model_name='telemetrysnapshot',
            name='telemetry_t_connect_a3f8bd_idx',
        ),
        migrations.RemoveField(
            model_name='telemetrysnapshot',
            name='recorded_at',
        ),
        migrations.AddField(
            model_name='telemetrysnapshot',
            name='recorded_date',
            field=models.DateField(auto_now_add=True, default=datetime.date(2026, 4, 10)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='telemetrysnapshot',
            name='recorded_time',
            field=models.TimeField(auto_now_add=True, default=datetime.time(6, 57, 25, 282619)),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='telemetrysnapshot',
            index=models.Index(fields=['-recorded_date', '-recorded_time'], name='telemetry_t_recorde_e1bfa7_idx'),
        ),
        migrations.AddIndex(
            model_name='telemetrysnapshot',
            index=models.Index(fields=['connected', '-recorded_date', '-recorded_time'], name='telemetry_t_connect_930a38_idx'),
        ),
    ]
