# Generated by Django 5.2.11 on 2026-04-10 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0006_alter_telemetrysnapshot_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissionTelemetryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=255)),
                ('battery', models.IntegerField(blank=True, null=True)),
                ('altitude_m', models.FloatField(blank=True, null=True)),
                ('flight_time', models.IntegerField(blank=True, null=True)),
                ('pitch', models.IntegerField(blank=True, null=True)),
                ('roll', models.IntegerField(blank=True, null=True)),
                ('yaw', models.IntegerField(blank=True, null=True)),
                ('temp_c', models.IntegerField(blank=True, null=True)),
                ('gps_lat', models.FloatField(blank=True, null=True)),
                ('gps_lon', models.FloatField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['recorded_at'],
            },
        ),
    ]
