# Generated by Django 5.2.11 on 2026-04-15 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0007_missiontelemetrylog'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='telemetrysnapshot',
            name='telemetry_t_recorde_e1bfa7_idx',
        ),
        migrations.RemoveIndex(
            model_name='telemetrysnapshot',
            name='telemetry_t_connect_930a38_idx',
        ),
        migrations.RemoveField(
            model_name='livesystemstate',
            name='ble_active',
        ),
        migrations.RemoveField(
            model_name='livesystemstate',
            name='last_error',
        ),
        migrations.AddField(
            model_name='telemetrysnapshot',
            name='gps_sats',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='telemetrysnapshot',
            name='gps_status',
            field=models.CharField(default='searching', max_length=50),
        ),
    ]
