# Generated by Django 5.2.11 on 2026-04-15 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0008_remove_telemetrysnapshot_telemetry_t_recorde_e1bfa7_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telemetrysnapshot',
            name='drone_snr',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='telemetrysnapshot',
            name='esp32_rssi',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
