# Generated by Django 5.2.11 on 2026-04-23 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0009_telemetrysnapshot_drone_snr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livesystemstate',
            name='pitch',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livesystemstate',
            name='roll',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livesystemstate',
            name='yaw',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
