# Generated by Django 6.0.2 on 2026-02-21 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MissionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Active Plan', max_length=120)),
                ('altitude', models.FloatField(default=100.0)),
                ('speed', models.FloatField(default=15.0)),
                ('mode', models.CharField(default='Stabilize', max_length=40)),
                ('status', models.CharField(choices=[('inactive', 'inactive'), ('queued', 'queued'), ('running', 'running'), ('completed', 'completed'), ('failed', 'failed'), ('cancelled', 'cancelled')], default='inactive', max_length=12)),
                ('active_index', models.IntegerField(default=-1)),
                ('message', models.CharField(blank=True, default='', max_length=255)),
                ('gps', models.CharField(default='Weak', max_length=20)),
                ('battery', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MissionStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1)),
                ('type', models.CharField(max_length=20)),
                ('val', models.FloatField(default=1.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='missions.missionplan')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
