# Generated by Django 5.2.11 on 2026-03-14 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CacaoDetectionLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('healthy_count', models.IntegerField(default=0)),
                ('unhealthy_count', models.IntegerField(default=0)),
            ],
        ),
    ]
