# Generated by Django 5.2.11 on 2026-03-18 07:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detections', '0002_alter_cacaodetectionlog_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cacaodetectionlog',
            name='session_id',
            field=models.CharField(db_index=True, default=uuid.uuid4, max_length=100),
        ),
    ]
