# Generated by Django 5.2.11 on 2026-03-27 07:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detections', '0003_cacaodetectionlog_session_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cacaodetectionlog',
            old_name='timestamp',
            new_name='start_time',
        ),
        migrations.AddField(
            model_name='cacaodetectionlog',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='cacaodetectionlog',
            name='session_id',
            field=models.CharField(db_index=True, default=uuid.uuid4, max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='DetectedCacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_id', models.IntegerField()),
                ('status', models.CharField(max_length=20)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detected_pods', to='detections.cacaodetectionlog')),
            ],
            options={
                'unique_together': {('session', 'track_id')},
            },
        ),
    ]
