# Generated by Django 5.2.11 on 2026-04-09 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detections', '0004_rename_timestamp_cacaodetectionlog_start_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cacaodetectionlog',
            name='flight_plan_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
