# Generated by Django 5.2.11 on 2026-04-10 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detections', '0005_cacaodetectionlog_flight_plan_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectedcacao',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='detections/'),
        ),
        migrations.AddField(
            model_name='detectedcacao',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detectedcacao',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
