# Generated by Django 5.2.11 on 2026-04-23 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detections', '0006_detectedcacao_image_detectedcacao_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectedcacao',
            name='pitch',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detectedcacao',
            name='roll',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detectedcacao',
            name='yaw',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
